reviews:
  auto: true               # Automatically review new PRs
  summarize: true          # Always include a summary report
  style: "detailed"        # Options: concise | detailed
  language: "en"

  # Always review the whole repo (not just diffs)
  scope:
    - architecture
    - maintainability
    - performance
    - readability
    - security
    - testing
    - documentation
    - best_practices

report:
  format: markdown
  sections:
    - title: "ðŸ“Š Overall Assessment"
      content: >
        Provide a big-picture analysis of the entire codebase, including backend
        and frontend layers, highlighting major strengths and risks.

    - title: "âœ… Strengths"
      content: >
        Note clean design choices, modular patterns, proper dependency
        injection, REST API design, React component architecture, and
        consistency.

    - title: "âš ï¸ Issues / Risks"
      content: >
        Identify critical problems in code quality, maintainability, scalability,
        and security. Include backend (Spring Boot/Java) and frontend
        (React/TypeScript) concerns.

    - title: "ðŸ’¡ Suggestions"
      content: >
        Provide actionable recommendations to improve the codebase. Cover
        database design, API contracts, React state management, and error
        handling.

    - title: "ðŸ§ª Testing & Coverage"
      content: >
        Evaluate unit, integration, and end-to-end tests. Point out missing
        coverage or untested edge cases.

    - title: "ðŸ“š Documentation & Readability"
      content: >
        Check README, API docs, inline comments, and developer onboarding
        materials. Suggest improvements.

path_excludes:             # Exclude noisy/unnecessary files
  - "node_modules/"
  - "dist/"
  - "build/"
  - "target/"
  - "*.min.js"
  - "*.lock"
  - "*.log"
  - "*.class"
  - ".git/"
