server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bankingdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    # Railway-style DATABASE_URL (uncomment if Railway provides   this)
    # url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bankingdb}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:1800000}