spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    hikari:
      maximum-pool-size: ${PROD_DB_POOL_SIZE:20}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: ${PROD_DDL_AUTO:update}
    show-sql: ${PROD_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT:6379}
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

jwt:
  secret: ${PROD_JWT_SECRET}
  expiration: ${PROD_JWT_EXPIRATION:1800000}

logging:
  level:
    org.springframework.security: ${PROD_SECURITY_LOG_LEVEL:INFO}
    com.example.bankingplatform: ${PROD_LOG_LEVEL:INFO}
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"