package com.example.bankingplatform.audit;

public enum AuditAction {
    // Authentication actions
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,

    // User management
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,

    // Account management
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_STATUS_CHANGED,
    ACCOUNT_DELETED,
    BALANCE_UPDATED,

    // Transaction actions
    TRANSACTION_CREATED,
    TRANSACTION_PROCESSED,
    TRANSACTION_CANCELLED,
    TRANSACTION_FAILED,

    // Billing actions
    BILLING_CREATED,
    BILLING_UPDATED,
    BILLING_STATUS_CHANGED,
    BILLING_PAYMENT_PROCESSED,
    BILLING_CANCELLED,
    BILLING_DISCOUNT_APPLIED,
    BILLING_DELETED,

    // Loan actions
    LOAN_CREATED,
    LOAN_APPROVED,
    LOAN_REJECTED,
    LOAN_DISBURSED,
    LOAN_PAYMENT_PROCESSED,
    LOAN_STATUS_CHANGED,
    LOAN_MARKED_DELINQUENT,
    LOAN_DELETED,

    // Report actions
    REPORT_REQUESTED,
    REPORT_GENERATED,
    REPORT_DOWNLOADED,
    REPORT_FAILED,
    REPORT_CANCELLED,
    REPORT_EXPIRED,

    // Administrative actions
    ADMIN_ACCESS,
    SYSTEM_CONFIG_CHANGED,
    DATA_EXPORT,

    // Security events
    SUSPICIOUS_ACTIVITY,
    UNAUTHORIZED_ACCESS,
    API_RATE_LIMITED,
    SESSION_EXPIRED
}